/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MoodsRouteImport } from './routes/moods'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BoutiquesRouteImport } from './routes/boutiques'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as MoodsSlugRouteImport } from './routes/moods.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodsRoute = MoodsRouteImport.update({
  id: '/moods',
  path: '/moods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesRoute = BoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodsSlugRoute = MoodsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MoodsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boutiques': typeof BoutiquesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/moods': typeof MoodsRouteWithChildren
  '/newsletter': typeof NewsletterRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/moods/$slug': typeof MoodsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boutiques': typeof BoutiquesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/moods': typeof MoodsRouteWithChildren
  '/newsletter': typeof NewsletterRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/moods/$slug': typeof MoodsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boutiques': typeof BoutiquesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/moods': typeof MoodsRouteWithChildren
  '/newsletter': typeof NewsletterRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/moods/$slug': typeof MoodsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutiques'
    | '/cart'
    | '/contact'
    | '/journal'
    | '/login'
    | '/moods'
    | '/newsletter'
    | '/our-story'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/moods/$slug'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boutiques'
    | '/cart'
    | '/contact'
    | '/journal'
    | '/login'
    | '/moods'
    | '/newsletter'
    | '/our-story'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/moods/$slug'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/boutiques'
    | '/cart'
    | '/contact'
    | '/journal'
    | '/login'
    | '/moods'
    | '/newsletter'
    | '/our-story'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/moods/$slug'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutiquesRoute: typeof BoutiquesRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  MoodsRoute: typeof MoodsRouteWithChildren
  NewsletterRoute: typeof NewsletterRoute
  OurStoryRoute: typeof OurStoryRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moods': {
      id: '/moods'
      path: '/moods'
      fullPath: '/moods'
      preLoaderRoute: typeof MoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques': {
      id: '/boutiques'
      path: '/boutiques'
      fullPath: '/boutiques'
      preLoaderRoute: typeof BoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moods/$slug': {
      id: '/moods/$slug'
      path: '/$slug'
      fullPath: '/moods/$slug'
      preLoaderRoute: typeof MoodsSlugRouteImport
      parentRoute: typeof MoodsRoute
    }
  }
}

interface MoodsRouteChildren {
  MoodsSlugRoute: typeof MoodsSlugRoute
}

const MoodsRouteChildren: MoodsRouteChildren = {
  MoodsSlugRoute: MoodsSlugRoute,
}

const MoodsRouteWithChildren = MoodsRoute._addFileChildren(MoodsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutiquesRoute: BoutiquesRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  MoodsRoute: MoodsRouteWithChildren,
  NewsletterRoute: NewsletterRoute,
  OurStoryRoute: OurStoryRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
